### ISSUE TITLE
getProductPerPageOptions should be checked if null

### ISSUE THREAD

**Issue by rudibatt** [FACT-Finder/FACT-Finder-PHP-Framework#11]
PHP Fatal error: Call to a member function getSelectedOption() on a non-object in factfinder/lib/FACTFinder/Json66/SearchAdapter.php on line 171

There are circumstances, where the result might be incomplete so for example the getProductsPerPageOptions does return an empty array although there is a result. 
This should be solved by returning an "empty PPP Object" or checking the return value before calling methods on it.

**Comment by Estigy** [comment]
Wie sieht es denn mit der Behebung dieses Fehlers aus?
Der Bug wurde vor über 3 Wochen gemeldet und tritt bei meinem Kunden noch immer auf.
